id: PE9E89C89
initial_creation_type: input
source_metadata:
  Title: Kriyāsaṁgrahapañjikā
  Editor: H. T. Bakker, Groningen
  Publisher: Egbert Forsten
  Place of Publication: Ryugen Taemura
  Year: '2004'
  Kriyāsaṁgrahapañjikā:
    Text Version: Romanized
    Input Personnel: Milan Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:17:16.567394'
last_modified_at: '2022-03-08T17:17:16.567402'
